services:

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"

  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # Fake credentials are fine for DynamoDB Local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      DYNAMODB_ENDPOINT_URL: http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    restart: on-failure
